### ISSUE TITLE
Invalid assert in about_printing.c:27

### ISSUE THREAD

**Issue by Spiderpig86** [c-koans/c_koans#4]
There is a possible issue in the assert flag where it is expecting "A" from stdout, but a garbage result is actually returned from the stream.
Thanks for making this tho :)

**Comment by enginn2** [comment]
The same issue also pops up in about_io.c where contents of stdout and stderr are checked with the Criterion function cr_assert_file_contents_eq_str(). Below is the excerpt of code that I got stuck. Great work, please fix this so I can pass all the tests :)

`    /*
        For this koan, output "Hello World" to both stdout and stderr.
	<stdio.h> provides variables for accessing the streams, which are just
	the names that we have been referring to them until now
	(stdin, stdout, and stderr)
    */

    fputs("Hello World", TODO_FP);
    fputs("Hello World", TODO_FP);

    cr_assert_file_contents_eq_str(stdout, "Hello World");
    cr_assert_file_contents_eq_str(stderr, "Hello World");
`

**Comment by brian-gavin** [comment]
I'll look into this. Apologies for taking so long to respond!
